(source gnu)
(source marmalade)
(source melpa)

(depends-on "auto-complete")
(depends-on "evil")
(depends-on "flycheck")
(depends-on "flycheck-color-mode-line")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "projectile")
(depends-on "rainbow-delimiters")
(depends-on "solarized-theme")
(depends-on "use-package")
(depends-on "yasnippet")